apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nuodbs.nuodb.com
spec:
  group: nuodb.com
  names:
    kind: Nuodb
    listKind: NuodbList
    plural: nuodbs
    singular: nuodb
  scope: Namespaced
  version: v1alpha1
