---
# defaults file for mongodb
mongodb_user: exampleusr
mongodb_password: d3f4ultP4ssw0rd
mongodb_database: exampledb
mongodb_admin_password: 4dm1nP4ssw0rd
memory_limit: 512Mi
k8s_name: "{{ meta.name | default('mongodb') }}"
namespace: "{{ meta.namespace | default('mongodb') }}"
image: "{{ lookup('env','RELATED_IMAGE_DB') | quote }}"
