{{- if .Values.instana.agent.key -}}
{{- if .Values.instana.zone -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.instana.agent.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.instana.agent.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.instana.agent.name }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8}}
{{- end }}
    spec:
      serviceAccount: {{ .Values.serviceAccount }}
      hostIPC: true
      hostNetwork: true
      hostPID: true
      containers:
        - name: {{ .Values.instana.agent.name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INSTANA_AGENT_LEADER_ELECTOR_PORT
              value: {{ .Values.instana.leaderElectorPort | quote }}
            - name: INSTANA_ZONE
              value: {{ .Values.instana.zone | quote }}
            - name: INSTANA_AGENT_ENDPOINT
              value: {{ .Values.instana.agent.endpoint.host | quote }}
            - name: INSTANA_AGENT_ENDPOINT_PORT
              value: {{ .Values.instana.agent.endpoint.port | quote }}
            - name: INSTANA_AGENT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.instana.agent.name }}-secret
                  key: key
            {{- if .Values.instana.agent.proxyHost }}
            - name: INSTANA_AGENT_PROXY_HOST
              value: {{ .Values.instana.agent.proxyHost | quote }}
            {{- end }}
            {{- if .Values.instana.agent.proxyPort }}
            - name: INSTANA_AGENT_PROXY_PORT
              value: {{ .Values.instana.agent.proxyPort | quote }}
            {{- end }}
            {{- if .Values.instana.agent.proxyProtocol }}
            - name: INSTANA_AGENT_PROXY_PROTOCOL
              value: {{ .Values.instana.agent.proxyProtocol | quote }}
            {{- end }}
            {{- if .Values.instana.agent.proxyUser }}
            - name: INSTANA_AGENT_PROXY_USER
              value: {{ .Values.instana.agent.proxyUser | quote }}
            {{- end }}
            {{- if .Values.instana.agent.proxyPassword }}
            - name: INSTANA_AGENT_PROXY_PASSWORD
              value: {{ .Values.instana.agent.proxyPassword | quote }}
            {{- end }}
            {{- if .Values.instana.agent.proxyUseDNS }}
            - name: INSTANA_AGENT_PROXY_USE_DNS
              value: {{ .Values.instana.agent.proxyUseDNS | quote }}
            {{- end }}
            {{- if .Values.instana.agent.httpListen }}
            - name: INSTANA_AGENT_HTTP_LISTEN
              value: {{ .Values.instana.agent.httpListen | quote }}
            {{- end }}
            - name: JAVA_OPTS
              value: "-Xmx{{ div .Values.computeResources.requests.memory 3 }}M -XX:+ExitOnOutOfMemoryError"
            - name: INSTANA_AGENT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: run
              mountPath: /var/run/docker.sock
            - name: sys
              mountPath: /sys
            - name: log
              mountPath: /var/log
            - name: machine-id
              mountPath: /etc/machine-id
            - name: configuration
              subPath: configuration.yaml
              mountPath: /root/configuration.yaml
          livenessProbe:
            httpGet:
              path: /status
              port: 42699
            initialDelaySeconds: 75
            periodSeconds: 5
          resources:
            requests:
              memory: "{{ .Values.computeResources.requests.memory }}Mi"
              cpu: {{ .Values.computeResources.requests.cpu }}
            limits:
              memory: "{{ .Values.computeResources.limits.memory }}Mi"
              cpu: {{ .Values.computeResources.limits.cpu }}
        - name: {{ .Values.instana.agent.name }}-leader-elector
          image: gcr.io/google-containers/leader-elector:0.5
          env:
            - name: INSTANA_AGENT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args: ["--election=instana", "--http=0.0.0.0:{{ .Values.instana.leaderElectorPort }}", "--id=$(INSTANA_AGENT_POD_NAME)"]
          resources:
            requests:
              cpu: 0.1
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /status
              port: 42699
            initialDelaySeconds: 75
            periodSeconds: 5
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8}}
{{- end }}
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: run
          hostPath:
            path: /var/run/docker.sock
        - name: sys
          hostPath:
            path: /sys
        - name: log
          hostPath:
            path: /var/log
        - name: machine-id
          hostPath:
            path: /etc/machine-id
        - name: configuration
          configMap:
            name: instana-configuration
{{- end -}}
{{- end -}}
