apiVersion: apps/v1
kind: Deployment
metadata:
  name: ectd-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ectd-helm
  template:
    metadata:
      labels:
        name: ectd-helm
    spec:
      serviceAccountName: ectd-helm
      containers:
        - name: ectd-helm
          # Replace this with the built image name
          image: quay.io/dhoover103/etcd-helm-operator:v0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ectd-helm"
            - name: RELATED_IMAGE_STATEFULSET
              value: k8s.gcr.io/etcd-amd64:3.2.26
