kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ectd-helm
subjects:
- kind: ServiceAccount
  name: ectd-helm
roleRef:
  kind: Role
  name: ectd-helm
  apiGroup: rbac.authorization.k8s.io
