apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"repomgr.sonatype.com/v1alpha1","kind":"Nexus","metadata":{"name":"nexus-operator"},"spec":{"maxMemory":"1Gi","nexusVersion":"3.16.0-01-rhel-2","size":3,"volumeCapacity":"2Gi"}}]'
    capabilities: Basic Install
    categories: "Integration & Delivery"
    description: Description of the nexus repository manager
    containerImage: quay.io/dhoover103/repomgr-operator
    createdAt: 2019-07-24T14:03:24Z
    support: placeholder
    certified: "false"
    repository: https://github.com/dhoover103/nexus-operator.git
  name: nexus-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Nexus
      name: nexus.repomgr.sonatype.com
      version: v1alpha1
  description: Placeholder description
  displayName: Nexus Operator
  icon:
    - base64data:
      mediatype: "image/png"
  install:
    spec:
      deployments:
      - name: nexus-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: nexus-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: nexus-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/dhoover103/repomgr-operator:v0.0.1
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: nexus-operator
                image: quay.io/dhoover103/repomgr-operator:v0.0.1
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: nexus-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - nexus-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - repomgr.sonatype.com
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        serviceAccountName: nexus-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  keywords: ['repository manager']
  links:
    - name: placeholder
      url: http://sonatype.example.operator.com/
  maintainers:
    - name: RHSCL
      email: RHSCL@example.com
  provider: 
    name: placeholder
  version: 0.0.1
