apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [{
       "apiVersion": "apm.instana.com/v1alpha1",
       "kind": "Instana",
       "metadata": {
          "name": "example-instana"
       },
       "spec": {
          "image": {
             "name": "registry.connect.redhat.com/instana/agent",
             "tag": "latest",
             "pullPolicy": "IfNotPresent"
          },
          "instana": {
             "zone": "k8s-cluster-name",
             "leaderElectorPort": 42655,
             "agent": {
                "name": "instana-agent",
                "endpoint": {
                   "host": "saas-us-west-2.instana.io",
                   "port": 443
                }
             }
          },
          "podAnnotations": {},
          "serviceAccount": "instana-agent",
          "tolerations": [],
          "computeResources": {
             "requests": {
                "memory": 512,
                "cpu": 0.5
             },
             "limits": {
                "memory": 512,
                "cpu": 1.5
             }
          }
       }
      }]
    categories: "Monitoring,OpenShift Optional"
    capabilities: "Basic Install"
    certified: "false"
    containerImage: quay.io/rhc4tp/instana-operator:v0.0.4
    createdAt: 2019-04-02T12:59:59Z
    description: Deploy the Instana agent from a helm chart onto your Kubernetes or OpenShift cluster
    repository: https://github.com/RHC4TP/operators/tree/master/partners/instana-operator
    support: Red Hat Connect
  name: instana-operator.v0.0.4
  namespace: "placeholder"
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Instana Operator by Red Hat Partner Connect
        displayName: Instana Operator
        kind: Instana
        name: instanas.apm.instana.com
        resources:
          - kind: DaemonSet
            name: ""
            version: apps/v1
          - kind: Pod
            name: ""
            version: v1
          - kind: Secret
            name: ""
            version: v1
          - kind: ConfigMap
            name: ""
            version: v1
        specDescriptors:
          - description: Instana agent container image name
            displayName: Image Name
            path: image.name
          - description: Instana agent container image tag
            displayName: Image Tag
            path: image.tag
          - description: Image pull policy stating whether or not to pull from the local image store
            displayName: Pull Policy
            path: image.pullPolicy
          - description: Zone Name given to this environment for Instana
            displayName: Zone Name
            path: instana.zone
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:core:v1:ConfigMap'
          - description: Port that the leader elector will listen on
            displayName: Leader Elector Port
            path: instana.leaderElectorPort
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:core:v1:ConfigMap'
          - description: Instana agent key
            displayName: Agent Key
            path: instana.agent.key
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:core:v1:Secret'
          - description: Name to use for Instana agent k8s resources
            displayName: K8s Name
            path: instana.agent.name
          - description: Endpoint hostname that Instana agent will connect to
            displayName: Endpoint Hostname
            path: instana.agent.endpoint.host
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:core:v1:ConfigMap'
          - description:  Endpoint Port that Instana agent will connect to
            displayName: Endpoint Port
            path: instana.agent.endpoint.port
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:core:v1:ConfigMap'
          - description:  Annotations to be added to pods
            displayName: Pod Annotations
            path: podAnnotations
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:core:v1:Pod'
          - description: Service account name used to deploy Instana agent pods
            displayName: Service Account Name
            path: serviceAccount
          - description: Tolerations for pod assignment
            displayName: Tolerations
            path: tolerations
          - description: Define resources requests and limits for individual Pods
            displayName: Compute Resources
            path: computeResources
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:resourceRequirements'
        statusDescriptors:
          - description: Current deployed state
            displayName: Conditions
            path: conditions
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.conditions'
        version: v1alpha1
  description: |
    This is an Operator for Instana, developed using the Instana helm chart available at [Instana's GitHub](https://github.com/instana/instana-agent-helm-chart).
    
    The operator will deploy the Instana agent (using the helm chart) on your Kubernetes or OpenShift cluster as a Daemonset.

    ## Prerequisites
    The Instana Operator will (by default) deploy the latest version of Instana from the Red Hat Container Catalog.
    The image will pull from the [Red Hat Container Catalog](https://access.redhat.com/containers), which will require the following:

    * RHN account (https://access.redhat.com)
    * RHCC Image pull secret in your project/namespace or [Red Hat Container Registry Authentication](https://access.redhat.com/RegistryAuthentication) setup on your OpenShift cluster

    To create an `rhcc` secret using docker (requires root/sudo or you must be in the docker group):
    ```
    # docker login -u <username> registry.connect.redhat.com
    Password:
    Login Succeeded
    # oc create secret generic rhcc --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson
    ```

    To create an `rhcc` secret using podman:
    ```
    $ podman login -u <username> registry.connect.redhat.com
    Password:
    Login Succeeded!
    $ oc create secret generic rhcc --from-file=.dockerconfigjson=$XDG_RUNTIME_DIR/containers/auth.json --type=kubernetes.io/dockerconfigjson
    ```

    To link the `rhcc` secret to the `default` service account to use as an image pull secret in the current project/namespace:
    ```
    $ oc secrets link default rhcc --for=pull
    ```

    ## Required Parameters

    There is only one required parameter, and that is the Agent Key available by logging into [Instana](https://instana.io).

    Note that the Agent Key is kept in a base64-encoded K8s Secret, however the key is also visible as plain text within the Custom Resource spec.

    Values listed below are relative to the `spec:` field in the Custom Resource.

    * **instana.agent.key** - Your Instana Agent Key

    ## Advanced Tunables

    This is a list of all supported (but optional) parameters that can be passed to the Operator via the Custom Resource:

    Values are relative to the `spec:` field in the Custom Resource.

    * **image.name** - The full path to the Instana container image (defaults to `registry.connect.redhat.com/instana/agent`)
    * **image.tag** - The container image tag (defaults to `:latest`)
    * **image.pullPolicy** - The pullPolicy to use when pulling the image (defaults to `IfNotPresent`)
    * **instana.agent.name** - Name to use for the K8s resources created by the Operator (defaults to `instana-agent`)
    * **instana.agent.endpoint.host** - The hostname of the endpoint that the agent will connect to  (defaults to `saas-us-west-2.instana.io`)
    * **instana.agent.endpoint.port** - The TCP port that the agent will connect on
    * **podAnnotations** - Annotations to be added to pods (defaults to an empty key/value dictionary)
    * **serviceAccount** - The name of the service account used to deploy Instana (NOTE: This **must** match what is defined in the ClusterServiceVersion under `clusterpermissions:`)
    * **tolerations** - Tolerations for pod assignment (defaults to an empty list/array)
    * **computeResources** - Pod resource limits (defaults are `requests.cpu: 0.5`, `requests.memory: 512`, `limits.cpu: 1.5 ` and `limits.memory: 512`)
  displayName: Instana Operator
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAA/0AAACPCAYAAACoPbs3AAACzHpUWHRSYXcgcHJvZmlsZSB0eXBlIGV4aWYAAHja5ZVbktwgDEX/WUWWgCSExHIwj6rsIMvPBTPd6ZlJqvL4C5QBy0LAPYDD+PZ1hi9IFIuHpOa55ByRUkmFKxoe73TXFNMud5o9yrG+2IPP04lhWi63W8zjrqnCrs8Olo79erUHayeOn0Dnw1tAWSMzGsfPTyDh207nPZTTr6YflnOerHdYOk7v35NBjK6IJxx4CElE6WsUwQykSEWddomB13e0k8guf6JdeDTficfyuXaxHg95lSLEfBzyO42OnfRz7bZCP86I3pr8+kHk0eWDdnN2n3Pcq6spQ6kczqLiCbFbcLwgpexuGdnwKNq2c0F2LLGBWAfNC7kFKsRQc1KiTpUmjV03aphi4sGGmrmxbJuLceG2oaSVabIBTw/iYNVATWDmx1xoj1v2eI0cI3eCJxOCEXp8yOEz45/kR6A519YlWmKybK1Q8trTmMYit0p4AQjNo6lufXcOD6zPtMAKCOqW2bHAGq87xKX03FuyOQv8NKYQ76NB1k8ASISxFZMhAYGYSZQyRWM2Iujo4FMxc5bEFwiQKncKE2xEMuA4r7HRx2j7svJtxtUCECpZDGhwgAArJcX+seTYQ1VFU1DVrKauRWuWnLLmnC2vO6qaWDK1bGZuxaqLJ1fPbu5evBYugitMSy4WipdSasWgFaEreld41HrxJVe69MqXXX6VqzZsn5aattyseSutdu7Scfx77ha699LroIGtNNLQkYcNH2XUib02ZaapM0+bPsusD2qH6is1ekfu19ToUFvE0vazJzWYzd5C0LpOdDEDMU4E4rYIYEPzYhadUuJFbjGLhXEolEGNdMHptIiBYBrEOunB7knul9yCpt/ixj8jFxa6f0EuLHSH3Edun1Drdf9R7tO4TuHSNMrExQaH4ZW9rn/SH9fhbwP894EmKOH3HL4DMm/4oURTbi4AAAAGYktHRAD/AP8A/6C9p5MAAAAJcEhZcwAABZQAAAWUAS1M4KMAAAAHdElNRQfjBAMOKyocZNMXAAAL1UlEQVR42u3d0W4jRw4FUJeg///lztMEg0GckaXuLpL3HGCfFpuMqkgWr+xs1hcAAFc5PvzfL0cI23pS/5mpIyhkAIA6C6m9Der1pt6bOVNj7lYBawb1UvMOnXXdPjCjgQrzx3ywf3HvPbmH2XN19P2uBhfgQmvfgwF4z/055/kBXy2AWWQmuHP3Xvu+nLu5On55PII/u0YwBKvc4XJuDK8J96zW1Kn7cefuvvKdOe+MHht1z6vhBSRf5uFcDbPA8xUC59aFu1V3ZpI7cefuvuO9OWszVei3sFiODcTL7285MxrXhrtVd2aS+3Dv7r/7vTnnnP5qf9dryEVMv8jD2RpoQWcrEM6uDfer7swl9+He3f+Ee9Nj5uqIP3jaYrY0hAZpeH/+eW461Yf7VXfmkvtw7+5+0t3pLzO1hYe60xQ3fQ7LPmoke4a4X/SQz4C3FTXpMwj9aHSf1/Bk4Pm6YzXnc/gszsvn8Vn1lc9SLPQfChHnjHpwzu6Y0HtXt+hJUH9jPpOf9Cskn815+nOrE2B+r5gBzkkNOFNC71/oB4+A83HuoN4yesQMAMydQEI/BgDu3vm7azADcP+g3oZ+RqEfTQIA/s/OcP+gzoZ+VqEfMBTdA+gJUPPA0J76LvSvwItaalWD4K7dB2AGAJgvk/hJPwYDAMnz3RuE/gRG95TQD1gs3AtcxW/RmQGAuULh0J/0UFtKDAjcLWA+gR4AxvXU337SnxCGBX7A4wSYAQDmyUiv/Hr/5FAs8BsUuFPAfAK9AESH/qnhWOAHuHbhM2cBwC7hLJqE/l/L24QFbsrnAIDq7y0WVNQA0Cj0dw/Nwr5HB3cJYD4BEPXOfPKv7OsSooV9gL0zGPcOgIBLw9Df4WG3dBgcwP6+M4sFfry9qAFgk+fJD3yVYWHhAIsD9YKguhD4zaf/PyM9AnDeXN09U48q7+LzogM/il04PUOj+yR1DhyD70ao0XvOqG6PeHtRA3TaWarP1DKeF17AUezS+fn5aRIEDuHYZ2NS/x0NzkiP6B33D+fO1Pi+eqgXCi9xHj0SA//kz/T7Z/NFrbs0ozL7H/sXJCnRT0/3wAsPj+GP5Wh+/60id2feCH3sX1DVn/0LKgfapaeEfiwfYPETdqcsNmQup0If9i/gNH69n85LOKhNALxxcL+O/8ftK+yshH4MFbD4WSxB6PPuog5gOqEfoQAA4cXbif0LEPohcmGD6YufhRIA+xcd6mIV+Wu06yWhH+EAcntQT4O3V9hTA8BwQj+dWEBQE+ctf5ZIzAlBDby1ENBLQj+WGMjrQ30MCHv2L+g0F5Z+EvoxaFATiQvguuF/Awh8YP8CoR/LB1hGNof/9eZ/D2aDdxL7FzD4XRL60Syoi5lfAAj6gNmKWmBCDawmf82yhH40Ch4jwDyo/z56d1EHgNCPZQ5LidoAAG8sY+5+Nf1rlzpLoR+Y+jBZTIBpYhZUStYB0JTQT+dHxxKCGgEq9b4whv4ChH6ADcuJBQUA4P1daoc15O+x/UyFfro2yu4hRP3a+C78qxnAbPXeqgP1ADGEfiCR8A+z+zsxhAHgvRL6GbvoCG9qQ/gHwBtr/2LOPa+gXhL6AYR/gBILqjkJIPRjAdka2lAbwj9k86v9eGPtX+DdEvoBhH8AIQ8o2u8r5O95G6GfSc1iEVEbV4V/tQWW02rzzW8XYP8ChH7AUnLBFwAAANP5x6UGnbXQj0YF4R+gQxig7v6lJtBHhQn9WEQwTIV/MPt7zjRftAMg9GMJQX0I/wB4X+FHu01qDY/8V6IK/RhUWEyEf8A89daiJmAooR+hDjVyTfi3/MDsoOGdw9sKCP0QuARiOfmvLwAAwP6FO+yxE477DSqhH4EOdSL8A+aogKcegKGEfqYHLSwowj+Y82YW2L8gtn+EfixGqBXhH0DA86aCL1KH9pDQj+GFASv8g/nef04JeehPQOjHIkKbekkN/5YkAOxfqNNsp++DQj8aB49AzS8AALyzqAvcl11U6EfTML5uhH+gynJafR55a1ETgNCPBRFLi/APAPYvtt9Th/1uxL8SVegHOgV/4R8gYEElLlgBFxL6SXp0LCTC/6Twr55J7gHBCfQsIPQDIeHfFwAAAO/vErv2uE47Z+u7EfpJa3ABafYXAMI/gF/xx/4FCP2A8C/8Q9MaTwxMACD00y6YJS6NCP9qHAD7F+n7wtI/996R0A8I/3MfcgsWltPM5bT9ggrAeYR+0pYRS4nwLygBYP/yJpFZg5G7nNAPJIb/tAfHT/0BwQ7Qp5/vkS0J/SQ3jmGn/hLDP6jdgAVvyJ8f+xcg9AMI/5YtAKDBLuCLyE13JvRTIXAJQAj/6h4wZ7B/gd65gNAPkBn+LVyo1YGL3eDPAYDQj4VE+EH4V/sA2L8oeO5L7+y7O6Ef4LXwP/ULAEsXCHfmC8BgQj/pC4nFhHe+ABD8YXZt+pV47F/eHxD6AYR/4QoA8Na/sDdN3AXb3KHQj+YRehD+wXI6ezltt6Bi/wLOI/QDCP8WLwDgqh2Jzfua0I/BAMK/4A+YK94v9CFD+0boBwOR68K/JQp6zeLpPWsmoechkNCPpQTu+QLA8gWA/Yukd11NFblToR8EHoR/AG8ragTe2+/KE/rRQCD8W75QeznvjvcV9QFhhH4QeBD+AcD+5UzP3nOSdrrSdyv0Awj/li/ImztmCsIahBD68ehYTqgV/i1bJPMTKcD+BUI/QMQXAAAAn/BF6vzP/NIdC/1ooJrDEqr81F8P4J3xuc0U9aFOoDGhH0D4hwos+QAz9haEfmg3PCyi6AMAvDv2r06cX07P/PWuhX5gx2D6/T8I/uCfO7WgAnARoR+LiQVld8j3JYCQAoA3x/7V/9zsKEXvXOgHrg77HniPKoBZD9jRNhH60UQWlIpn5af+lnPUV+Ri5hxQI94gEPqBpAXeQ29RBwDq7072kv1ncQj9aCIhtOv5OHMAbwb2L+BNQj8AkLbI+4mU8wAQ+sFyUm5JTV7enTkA2L+oeUa+OKxzJofQDwBYxCi/oAJwHqEfy4klpct5OHMwN876+5onYP/CvQj9AHhgYXgP6SPAXmCmXqXMb1AJ/Wgkw82DRvVeQy+b5WELKupEz7ae7+6nmKcjAMtKw/NezgAwW8BbSNmz+PVnMlcLvGl+0k93BonHzWcHzuwvPWa2Yf/CXB3VK88fXBZAxQVxBX1WUM/myx0LqpkDXDFXfVlUMPQfCgkLCgIEYL7YL8D+ZQ8yU1vWxvr6+v7X+4/GH8zwATh3qQOLk/1CeAHM1Ka71GPowPU4CyYACHX+/N5U1AoyW7zH8MdMIQEAdgtg6jwyV3vY+q9EfQwO/F8hnw2SBxmAJXXgggrEzlUu8Ag6YN/MC56AnsIyZ78AbwVmamToV0gAAPYLoM/MMVN72fYbVI/gB8rjPJNvm5097hMs4s0XVGWkVkBmO8/DESgkABDi7BYA5qrQbyGhC982O3vcI1hSwduBzKZPhH7BHwAQ/gU51IvMYqbOJfRrIo8Ozh73BxZVADNV6AfhBfQMcNKiCt4SyAz/t/eI0O8xBg8+7gzsGuYD6A1zdSihH8MYZw96BwsqmGPOl6F3KPSjqXw+Z497ckYI/mBuYqYOJfQblM4TZ+9+QJ1R6Q6XWlU3gNCPgexzgp6YeF7uBMwUn9PnQm+c+vd5KFg0l89z05/TrFE7ZN+JmnOHXepErTpTZ9qbX/H/g5/0a+blXHH2cXfgHtQwYJb4zP0/izep/7msO/76DwWjaJ2rz+DPre7Zfo5+zRd3WKs+1KpzVRt0r6l//7oPBazAfH5/9k1/fjPHeZsfmbNYLbrDLnWx9IA3yUxlQl38WST++Ye6zXMEfMZJ52u4zzx784wz63c5O5rXwRFwBvYvcyC1Vs3Vvve4Xj2QQ6FkFQJtan85f9RK+/p1N3p+Wi0cAZ/f/mUWLOdorja4x/XTQzkUisfV46M2nb/5BXpev558jyusTs1m+5dzdFdX3+P69GAORdK+GDw2vQen+/MlgPpAv+tZ7F/OWK+aqXrtLf8AWxXACS7M4QgAAAAASUVORK5CYII= 
      mediatype: "image/png"
  install:
    spec:
      deployments:
      permissions:
        - rules:
          - apiGroups:
            - ""
            resources:
            - pods
            - services
            - endpoints
            - persistentvolumeclaims
            - events
            - configmaps
            - secrets
            verbs:
            - '*'
          - apiGroups:
            - ""
            resources:
            - namespaces
            verbs:
            - get
          - apiGroups:
            - apps
            resources:
            - deployments
            - daemonsets
            - replicasets
            - statefulsets
            verbs:
            - '*'
          - apiGroups:
            - monitoring.coreos.com
            resources:
            - servicemonitors
            verbs:
            - get
            - create
          - apiGroups:
            - apps
            resourceNames:
            - instana-operator
            resources:
            - deployments/finalizers
            verbs:
            - update
          - apiGroups:
            - apm.instana.com
            resources:
            - '*'
            verbs:
            - '*'
          serviceAccountName: instana-operator
      # Required cluster permissions for the instana-agent service account
      # Also includes SCCs required to run on OpenShift
      clusterPermissions:
        - rules:
          - verbs:
              - use
            apiGroups:
              - security.openshift.io
            resources:
              - securitycontextconstraints
            resourceNames:
              - privileged
              - hostaccess
              - hostnetwork
          - nonResourceURLs:
              - /version
              - /healthz
            verbs: 
              - get
          - apiGroups:
              - batch
            resources:
              - jobs
            verbs:
              - get
              - list
              - watch
          - apiGroups: 
              - apps
            resources:
              - deployments
              - replicasets
              - ingresses
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - ""
            resources:
              - namespaces
              - events
              - services
              - endpoints
              - nodes
              - pods
              - replicationcontrollers
              - componentstatuses
              - resourcequotas
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - ""
            resources:
              - endpoints
            verbs:
              - create
              - update
              - patch
          serviceAccountName: instana-agent
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - monitoring
    - apm
  links:
    - name: Instana Operator - RHC4TP GitHub
      url: https://github.com/RHC4TP/operators/tree/master/partners/instana-operator
    - name: Instana Documentation
      url: https://docs.instana.io
  maintainers:
    - email: connect@redhat.com
      name: Red Hat Partner Connect
  maturity: alpha
  provider:
    name: Red Hat Partner Connect
  version: 0.0.4
