apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: newrelics.apigw.newrelichq.com
spec:
  group: apigw.newrelichq.com
  names:
    kind: Newrelic
    listKind: NewrelicList
    plural: newrelics
    singular: newrelic
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
