apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: httpds.apache.example.com
spec:
  group: apache.example.com
  names:
    kind: HTTPD
    listKind: HTTPDList
    plural: httpds
    singular: httpd
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
