apiVersion: apps/v1
kind: Deployment
metadata:
  name: insightedge-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: insightedge-operator
  template:
    metadata:
      labels:
        name: insightedge-operator
    spec:
      serviceAccountName: insightedge-operator
      containers:
        - name: insightedge-operator
          # Replace this with the built image name
          image: quay.io/rhc4tp/gigaspaces-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "insightedge-operator"
