apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mariadbs.mariadb.example.com
spec:
  group: mariadb.example.com
  names:
    kind: MariaDB
    listKind: MariaDBList
    plural: mariadbs
    singular: mariadb
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
