apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: "{{ template "mariadb.name" . }}"
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Server | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: "{{ .Release.Name }}"
      app: {{ template "mariadb.name" . }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{ template "mariadb.name" . }}"
        release: "{{ .Release.Name }}"
        chart: {{ template "mariadb.chart" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | quote }}
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: "mariadb"
        image: {{ template "mariadb.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mariadb.fullname" . }}
              key: database-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "mariadb.fullname" . }}
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mariadb.fullname" . }}
              key: database-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ template "mariadb.fullname" . }}
              key: database-name
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec $MYSQL_PREFIX/bin/mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -p$MYSQL_PASSWORD -e 'SELECT 1'"]
          initialDelaySeconds: 5
          timeoutSeconds: 1
        {{- if .Values.resources }}
        resources:
          {{- if .Values.resources.limits }}
          limits:
            {{- if .Values.resources.limits.cpu }}
            cpu: {{ .Values.resources.limits.cpu | quote }}
            {{- end }}
            {{- if .Values.resources.limits.memory }}
            memory: {{ .Values.resources.limits.memory | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.resources.requests }}
          requests:
            {{- if .Values.resources.requests.cpu }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
            {{- end }}
            {{- if .Values.resources.requests.memory }}
            memory: {{ .Values.resources.requests.memory | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
        volumeMounts:
        - name: "{{ template "mariadb.name" . }}-data"
          mountPath: "/var/lib/mysql/data"
        {{- if .Values.db.config }}
        - name: config
          mountPath: /etc/opt/rh/rh-mariadb102/my.cnf
          subPath: my.cnf
        {{- end }}
      volumes:
      - name: "{{ template "mariadb.name" . }}-data"
        emptyDir: {}
      {{- if .Values.db.config }}
      - name: config
        configMap:
          name: {{ template "mariadb.fullname" . }}
      {{- end}}
