apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "etcd.sample-etcd.com/v1alpha1",
          "kind": "Etcd",
          "metadata": {
            "name": "example-etcd"
          },
          "spec": {
            "affinity": {},
            "auth": {
              "client": {
                "enableAuthentication": false,
                "secureTransport": false
              },
              "peer": {
                "enableAuthentication": false,
                "secureTransport": false,
                "useAutoTLS": false
              }
            },
            "clientPort": 2379,
            "component": "etcd",
            "extraEnv": [],
            "image": {
              "pullPolicy": "IfNotPresent",
              "repository": "k8s.gcr.io/etcd-amd64",
              "tag": "3.2.26"
            },
            "memoryMode": false,
            "nodeSelector": {},
            "peerPort": 2380,
            "persistentVolume": {
              "enabled": false
            },
            "replicas": 3,
            "resources": {},
            "tolerations": []
          }
        }
      ]
    capabilities: Basic Install
    catagories: ""
    description: "sample etcd operator"
    containerImage: ""
    createdAt: "2020-01-09"
    support: ""
  name: etcd-helm.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Placeholder description
  displayName: Etcd Helma
  icon:
    - base64data:
      mediatype: "image/png"
  install:
    spec:
      deployments:
      - name: ectd-helm
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ectd-helm
          strategy: {}
          template:
            metadata:
              labels:
                name: ectd-helm
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ectd-helm
                - name: RELATED_IMAGE_STATEFULSET
                  value: k8s.gcr.io/etcd-amd64:3.2.26
                image: quay.io/dhoover103/etcd-helm-operator:v0.0.1
                imagePullPolicy: Always
                name: ectd-helm
                resources: {}
              serviceAccountName: ectd-helm
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - ectd-helm
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - etcd.sample-etcd.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: ectd-helm
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.1
