apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: instana-agent
rules:
- verbs:
    - use
  apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - privileged
    - hostaccess
    - hostnetwork
- nonResourceURLs:
    - /version
    - /healthz
  verbs: 
    - get
- apiGroups:
    - batch
  resources:
    - jobs
  verbs:
    - get
    - list
    - watch
- apiGroups: 
    - apps
  resources:
    - deployments
    - replicasets
    - ingresses
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - namespaces
    - events
    - services
    - endpoints
    - nodes
    - pods
    - replicationcontrollers
    - componentstatuses
    - resourcequotas
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - create
    - update
    - patch
