kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: instana-agent
subjects:
- kind: ServiceAccount
  name: instana-agent
  namespace: REPLACE_NAMESPACE
roleRef:
  kind: ClusterRole
  name: instana-agent
  apiGroup: rbac.authorization.k8s.io
