apiVersion: apps/v1
kind: Deployment
metadata:
  name: instana-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: instana-operator
  template:
    metadata:
      labels:
        name: instana-operator
    spec:
      serviceAccountName: instana-operator
      containers:
        - name: instana-operator
          # Replace this with the built image name
          image: quay.io/rhc4tp/instana-operator:v0.0.2
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "instana-operator"
