apiVersion: v1
kind: Deployment
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: "{{ template "mariadb.name" . }}"
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Server | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: "{{ .Release.Name }}"
      app: {{ template "mariadb.name" . }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{ template "mariadb.name" . }}"
        release: "{{ .Release.Name }}"
        chart: {{ template "mariadb.chart" . }}
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: "mariadb"
        image: {{ template "mariadb.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: {{ .Values.rootUser.password | quote }}
        - name: MARIADB_USER
          value: "{{ .Values.db.user }}"
        - name: MARIADB_PASSWORD
          value: "{{ .Values.db.password }}"
        - name: MARIADB_NAME
          value: "{{ .Values.db.name }}"
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec mysql -h 127.0.0.1 -u $MARIADB_USER -D $MARIADB_DATABASE -p $MARIADB_PASSWORD" -e 'SELECT 1'"]
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: "512Mi"
        volumeMounts:
        - name: "{{ template "mariadb.name" . }}-data"
          mountPath: "/var/lib/mysql/data"
      volumes:
        - name: "{{ template "mariadb.name" . }}-data"
          emptyDir: {}
