apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nuodbs.nuodb.com
spec:
  group: nuodb.com
  names:
    kind: Nuodb
    listKind: NuodbList
    plural: nuodbs
    singular: nuodb
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
