apiVersion: apps/v1
kind: Deployment
metadata:
  name: airgap-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airgap-operator
  template:
    metadata:
      labels:
        name: airgap-operator
    spec:
      serviceAccountName: airgap-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "quay.io/dhoover103/airgap-operator:v0.0.1"
          imagePullPolicy: 'Always'
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "quay.io/dhoover103/airgap-operator:v0.0.1"
          imagePullPolicy: 'Always'
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "airgap-operator"
            - name: RELATED_IMAGE_DB
              value: "registry.access.redhat.com/rhscl/mongodb-36-rhel7:latest"
      volumes:
        - name: runner
          emptyDir: {}
