apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: {{ template "mariadb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  database-user:  {{ .Values.db.user | b64enc | quote }}
  database-password:  {{ .Values.db.password | b64enc | quote }}
  database-root-password:  {{ .Values.db.rootPassword | b64enc | quote }}
  database-name:  {{ default "sampledb" .Values.db.name | b64enc | quote }}

