# Default values for xap-zeppelin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gigaspaces/insightedge-enterprise
  tag: "14.0.1"
  pullPolicy: IfNotPresent #Always

nameOverride: insightedge-zeppelin

service:
  # type: Service type.
  type: NodePort
  port:
    internal: 9090
    api: 30990
