
{{$managerReplicas := (.Values.ha) | ternary 3 1 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "insightedge-manager.fullname" . }}
  labels:
    app: {{ template "insightedge-manager.name" . }}
    chart: {{ template "insightedge-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{$managerReplicas}}
  serviceName: {{ template "insightedge-manager.fullname" . }}-hs
  selector:
    matchLabels:
      selectorId: {{ template "insightedge-manager.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "insightedge-manager.name" . }}
        release: {{ .Release.name }}
        component: manager
        selectorId: {{ template "insightedge-manager.fullname" . }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: gigaspaces-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: EXT_JAVA_OPTIONS
            value: "{{.Values.java.options}}"
          command: ["tools/kubernetes/entrypoint.sh"]
          args:
            - "component=manager"
            - "verbose=true"
            - "java.heap={{ .Values.java.heap}}"
            - "managerReplicas={{$managerReplicas}}"
            - "release.namespace={{ .Release.Namespace }}"
            - "full.name={{ template "insightedge-manager.fullname" . }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.antiAffinity.enabled }}
      affinity:
         podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: selectorId
                    operator: In
                    values:
                     - {{ template "insightedge-manager.fullname" . }}
              topologyKey: "kubernetes.io/hostname"
{{ end }}
