apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: sematext-agent-operator.v0.0.1
  namespace: placeholder
  annotations: 
    alm-examples: |
      {
         "apiVersion": "apigw.sematext.com/v1alpha1",
         "kind": "Sematext",
         "metadata": {
            "name": "example-sematext"
         },
         "spec": {
            "image": {
               "repository": "registry.connect.redhat.com/sematext/sematext-agent-docker",
               "tag": "latest",
               "pullPolicy": "IfNotPresent"
            },
            "sematext": {
               "region": "US",
               "useHostNetwork": false,
               "name": "sematext-docker-agent",
               "config": null,
               "resources": {},
               "tolerations": [],
               "nodeSelector": {}
            }
         }
      }
    categories: "Networking,OpenShift Optional" 
    description: Deploy the Sematext agent from a helm chart onto your Kubernetes or OpenShift cluster
    containerImage: quay.io/rhc4tp/sematext-operator
    createdAt: 2019-04-11T13:16:59Z
    certified: "false"
    repository: https://github.com/nhartman1/sematext-operator.git
    support: Red Hat Connect
spec:
  apiservicedefinition: {}
  displayName: Sematext Operator
  description: |
    This is an Operator for Sematext. The operator will deploy the Sematext agent (using the helm chart) on your Kubernetes or Openshift cluster as a Daemonset.
  keywords: 
  - apigateway
  icon: []
  version: 0.0.1
  maturity: alpha
  maintainers:
  - name: Red Hat Partner Connect
    email: connect@redhat.com
  provider:
    name: Red Hat Partner Connect
  links:
  - name: Sematext Operator - Github
    url: https://github.com/nhartman1/sematext-operator
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: sematext-agent
        rules:
        - verbs:
            - use
          apiGroups:
            - security.openshift.io
          resources:
            - securitycontextconstraints
          resourceNames:
            - privileged
            - hostaccess
            - hostnetwork
      permissions:
      - serviceAccountName: sematext-operator
        rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - sematext-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - apigw.sematext.com
          resources:
          - '*'
          verbs:
          - '*'
      deployments:
      - name: sematext-operator
        spec: 
      replicas: 1
      selector:
        matchLabels:
          name: sematext-operator
      template:
        metadata:
          labels:
            name: sematext-operator
        spec:
          serviceAccountName: sematext-operator
          containers:
            - name: sematext-operator
              # Replace this with the built image name
              image: quay.io/rhc4tp/sematext-operator:v0.0.1
              imagePullPolicy: Always
              env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: "sematext-operator"

  customresourcedefinitions:
    owned:
    - name: sematexts.apigw.sematext.com
      version: v1alpha1
      kind: Sematext
      displayName: Sematext Operator
      description: Sematext Operator by Red Hat Partner Connect
      resources:
          - kind: DaemonSet
            name: ""
            version: apps/v1
          - kind: Pod
            name: ""
            version: v1
          - kind: Secret
            name: ""
            version: v1
          - kind: ConfigMap
            name: ""
            version: v1
      specDescriptors:
      - description: Sematext agent container image name
        displayName: Image Name
        path: image.name
      - description: Sematext agent container image tag
        displayName: Image Tag
        path: image.tag
      - description: Sematext agent container repository
        displayName: Image Repository
        path: image.repository 
      - description: Image pull poslicy stating whether or not to pull from the local image store
        displayName: Pull Policy
        path: image.pullpolicy
      - description: Name of the agent
        displayName: sematext
        path: sematext.name
      - description: Name of the region you are located in
        displayName: Sematext Region
        path: sematext.region
      - description: Whether or not you are using Host Network
        displayName: useHostNetwork
        path: sematext.useHostNetwork
      - description: Configuration for Sematext agent 
        displayName: Config
        path: sematext.config
      - description: Resources used by Sematext agent
        displayName: Resources
        path: sematext.resources
        x-descriptors: 
        - 'urn:alm:descriptor:com.tectonic.ui:resourceRequirements'
      - description: Tolerations for pod assignment
        displayName: Tolerations
        path: sematext.tolerations
      - description: Selector for Node
        displayName: NodeSelector
        path: sematext.nodeSelector
        


        
