== Helm Chart Authoring Quickstart
In this guide, we'll create a basic Helm Chart for an example application (MariaDB). We've used the Tomcat Helm Chart as an example previously, so to show some variation we've authored a rather simplified example for MariaDB in order to demonstrate. You can find the actual Helm charts for Tomcat, MariaDB and a plethora of other apps (in human-readable text format) at https://github.com/helm/charts. 

First, you must install the Helm client if you haven't already. Download the latest Helm archive and extract the binary somewhere within your shell's `$PATH`:

----
# curl -LO https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz
# tar -xzvf helm-v2.11.0-linux-amd64.tar.gz -C /usr/local/bin/ --strip-components=1 */helm
----

NOTE: You'll need root permissions to install the `helm` binary into `/usr/local/bin` on your system

Once helm is installed, create a `mariadb` directory to house the chart's various files/folders, and change to that directory:

----
$ mkdir mariadb
$ cd mariadb/
----

Continue with creating the metadata or descriptive data file for the chart. Create a file named `Chart.yaml` in an editor, with the following contents:

----
apiVersion: v1
name: mariadb
description: A minimal chart to deploy a MariaDB database for testing.
version: 0.1.0
appVersion: 10.2
----

With that minimal set of descriptive fields (only 3 of which are required: `apiVersion`, `name` and `version`), we can move on with defining `values.yaml`:

----
image:
  registry: registry.access.redhat.com
  repository: rhscl/mariadb-102-rhel7
  tag: latest
  pullPolicy: IfNotPresent
db:
  user: sampleusr
  password:
  name: sampledb
  rootPassword:
  config: |-
    [mysqld]
    datadir=/var/lib/mysql/data
    basedir=/opt/rh/rh-mariadb102/root/usr
    plugin-dir=/opt/rh/rh-mariadb102/root/usr/lib64/mysql/plugin
    port=3306
    bind-address=0.0.0.0
    max_allowed_packet=16M
    symbolic-links=0
    skip_name_resolve
    ignore-db-dir=lost+found
    character-set-server=UTF8
    collation-server=utf8_general_ci
    general_log=0
    general_log_file=/var/lib/mysql/data/mysql-query.log

    [client]
    port=3306
    default-character-set=UTF8
----

NOTE: You'll need to set values for both the `password` and `rootPassword` fields in the `values.yaml` file above

In the above `values.yaml` example, we've defined several key/value pairs, the values of which will be plugged into K8s manifest templates later on. If you noticed that string values aren't quoted, it's because that will occur later when we define the templates. We also define a custom `my.cnf` file above in order to bind MariaDB to the IP address `0.0.0.0`, meaning all addresses in the container. Next, create the `templates/` folder which will house these manifest templates:

----
$ mkdir templates/
$ cd templates/
----

Next, we'll start by defining a Kubernetes Deployment template. Create a new file name `mariadb-deployment.yaml` with the following contents:

----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: "{{ template "mariadb.name" . }}"
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Server | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: "{{ .Release.Name }}"
      app: {{ template "mariadb.name" . }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{ template "mariadb.name" . }}"
        release: "{{ .Release.Name }}"
        chart: {{ template "mariadb.chart" . }}
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: "mariadb"
        image: {{ template "mariadb.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.db.rootPassword | quote }}
        - name: MYSQL_USER
          value: "{{ .Values.db.user }}"
        - name: MYSQL_PASSWORD
          value: "{{ .Values.db.password }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.db.name }}"
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec $MYSQL_PREFIX/bin/mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -p$MYSQL_PASSWORD -e 'SELECT 1'"]
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: "512Mi"
        volumeMounts:
        - name: "{{ template "mariadb.name" . }}-data"
          mountPath: "/var/lib/mysql/data"
        {{- if .Values.db.config }}
        - name: config
          mountPath: /etc/opt/rh/rh-mariadb102/my.cnf
          subPath: my.cnf
        {{- end }}
      volumes:
      - name: "{{ template "mariadb.name" . }}-data"
        emptyDir: {}
      {{- if .Values.db.config }}
      - name: config
        configMap:
          name: {{ template "mariadb.fullname" . }}
      {{- end}}
----

In review of the above Deployment template, you'll notice that the Go templating engine uses `{{   }}` to denote templated values. This syntax is essentially identical to the Jinja2 templating engine supported in Python and Ansible. It's hopefully clear that we're substituting values for container environment variables like `MYSQL_PASSWORD` with what was defined in `values.yaml`, where those fields are referenced using dot notation (eg: `.Values.db.password`). What's definitely unclear are references such as `.Release.Name` which is used to look up hard-coded info about Helm. What's also unclear are fields such as `mariadb.name` which we'll define in the next step. You may wonder why `mariadb.name` is the only above templated field that is quoted (eg: `"{{...}}"`), and we'll explain that next. The last thing to note at the end of the file is how we've defined conditional yaml blocks, which only get included in the generated K8s manifest if the `.Values.db.config` field is populated.

Let's go ahead and create a file name `_helpers.tpl` with the following contents:

----
{{/* vim: set filetype=mustache: */}}
{{/*
Expand the name of the chart.
*/}}
{{- define "mariadb.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "mariadb.fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "mariadb.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Return the proper image name
*/}}
{{- define "mariadb.image" -}}
{{- $registryName :=  .Values.image.registry -}}
{{- $repositoryName := .Values.image.repository -}}
{{- $tag := .Values.image.tag | toString -}}
{{- printf "%s/%s:%s" $registryName $repositoryName $tag -}}
{{- end -}}
----

Reviewing the above `_helpers.tpl` file, you'll see that it's a slightly varied form of template (in a format known as mustache). This file, and any other files in `templates/` that begin with an underscore, will not get rendered to a K8s manifest by Helm. It is therefore a stand-alone file, the contents of which can be referenced from any other file within the `templates/` directory. It is in this `_helpers.tpl` file where we satisfy the `mariadb.name`, `mariadb.fullname`, `mariadb.chart` and `mariadb.image` fields referenced in `mariadb-deployment.yaml`. To populate these fields, we are referencing fields from `Chart.yaml` (`.Chart.fieldname`), `values.yaml` (`.Values.fieldname`), and Helm release info (`.Release.fieldname`). The data is then formatted/translated by piping the data into other commands supported by the Go templating engine. The field values all get quoted by `printf` statements except for `mariadb.name`, which is why we quoted it separately in `mariadb-deployment.yaml`. In K8s yaml manifests, all string values must be quoted in order to be serialized by the K8s APIs.

The last template to create is the ConfigMap used to mount the custom `my.cnf` file (listed in `values.yaml`) into the MariaDB container as `/etc/opt/rh/rh-mariadb102/my.cnf`. Create a file named `mariadb-configmap.yaml` with the following contents:

----
{{- if .Values.db.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: {{ template "mariadb.name" . }}
    component: "master"
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  my.cnf: |-
{{ .Values.db.config | indent 4 }}
{{- end -}}
----

At this point, all of the templated variables have been defined and satisfied for the `mariadb-deployment.yaml` file. You'll first need to change into the parent directory of the helm chart, and also create a new project (namespace) to house the MariaDB resources:

----
$ cd ../../
$ oc new-project mariadb-test
----

Since MariaDB runs with a fixed UID (as specified in `mariadb-deployment.yaml`), you must grant the proper security context constraint of `anyuid` to the `default` service account for the newly created namespace (you will need to be logged in as `system:admin` in your cluster):

----
$ oc adm policy add-scc-to-user anyuid -z default
----

You can generate Kubernetes manifests from the chart by using the `helm template` command and piping the output to the `oc create` command (we also pass in `test` to use as `.Release.Name` to avoid the default value of `RELEASE-NAME` which breaks the K8s manifests):

----
$ helm template -n test mariadb | oc create -f -
----

You should now see the resources launching in Minishift. Once the MariaDB pod has initialized, you can enable connecting to the database from your host system by creating a `LoadBalancer` service:

----
$ oc expose deployment test-mariadb --type=LoadBalancer --name=mariadb-ingress
----

You can retrieve the port that was assigned to the service by issuing the following command, referencing the `NodePort` value:

----
$ oc describe svc mariadb-ingress
----

In order to connect, you'll need the client portion of MariaDB 10.2, which is available from Red Hat Software Collections. Once obtained, you can connect to the database by issuing the `mysql` command and substituting the `NodePort` :

----
mysql -h $(minishift ip) --port <NodePort> -u sampleusr -D sampledb --password
----
