apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: instanas.apm.instana.com
spec:
  group: apm.instana.com
  names:
    kind: Instana
    listKind: InstanaList
    plural: instanas
    singular: instana
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
